os:
  - osx
language: ruby
cache: bundler
rvm:
  - system

before_install:
  # There is a bug in travis. When using system ruby, bundler is not
  # installed and causes the default install action to fail.
  - sudo gem install bundler

after_install:
  - ./bin/pod repo update --silent

addons:
 code_climate:
   repo_token: 501acd9bc61d80ef6119b69ab42c52fa66cefddcc6724a1e93a79c3d3e32bf55  

